### ISSUE TITLE
Timezone is incorrect on remote workspaces

### ISSUE THREAD

**Issue by chrisstuartparry** [Ygilany/vscode-clock#3]
I'm in the UK and using this extension on VS Code Version: 1.91.0 (Universal) on macOS. When I use the Remote - SSH extension to connect to a remote development server, the timezone used for the clock seems to be changed to the timezone of the remote server rather than staying the same as my local machine. A toggle or fix for this would be appreciated.

**Comment by Ygilany** [comment]
will be released shortly
